//Define Clock source
#define MCU_CLOCK_SOURCE
#define MCU_CLOCK_SOURCE_HXT  // HXT, LXT, HIRC, LIRC
#define MCU_CLOCK_FREQUENCY   50000000  // Hz

//Define MCU Interfaces
// LCD
#define MCU_INTERFACE_SPI3
#define SPI3_CLOCK_SOURCE_HCLK // HCLK, PLL
#define PIN_SPI3_SS0_PD8
#define PIN_SPI3_SCLK_PD9
#define PIN_SPI3_MISO0_PD10
#define PIN_SPI3_MOSI0_PD11

// Timer 3, dedicate for 7seg
#define MCU_INTERFACE_TMR3
#define TMR3_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, EXT, LIRC, HIRC
#define TMR3_CLOCK_DIVIDER    1
#define TMR3_OPERATING_MODE   TIMER_PERIODIC_MODE // ONESHOT, PERIODIC, TOGGLE, CONTINUOUS
#define TMR3_OPERATING_FREQ   200  //Hz, Equals 5ms

// Timer 0
#define MCU_INTERFACE_TMR0
#define TMR0_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, EXT, LIRC, HIRC
#define TMR0_CLOCK_DIVIDER    1
#define TMR0_OPERATING_MODE   TIMER_PERIODIC_MODE // ONESHOT, PERIODIC, TOGGLE, CONTINUOUS
#define TMR0_OPERATING_FREQ   200  // Hz, Equals 5 ms

// // PWM output to Buzzer
// #define MCU_INTERFACE_PWM1
// #define PWM1_CH01_CLOCK_SOURCE_HXT
// #define PIN_PWM1_CH0_PB11

// // ADC7, for variable resistor
// #define MCU_INTERFACE_ADC
// #define ADC_CLOCK_SOURCE_HXT // HXT, LXT, PLL, HIRC, HCLK
// #define ADC_CLOCK_DIVIDER    1
// #define PIN_ADC7_PA7
// #define ADC_CHANNEL_MASK      ADC_CH_7_MASK
// #define ADC_INPUT_MODE        ADC_INPUT_MODE_SINGLE_END // SINGLE_END, DIFFERENTIAL
// #define ADC_OPERATION_MODE    ADC_OPERATION_MODE_SINGLE // SINGLE, SINGLE_CYCLE, CONTINUOUS

// // UART 0
// #define MCU_INTERFACE_UART0
// #define UART_CLOCK_SOURCE_HXT // HXT, LXT, PLL, HIRC
// #define UART_CLOCK_DIVIDER     3
// #define PIN_UART0_RX_PB0
// #define PIN_UART0_TX_PB1

// I2C 0
#define MCU_INTERFACE_I2C0
// #define I2C0_CLOCK_FREQUENCY  400000 // Hz
#define I2C0_CLOCK_FREQUENCY  100000 // Hz
#define PIN_I2C0_SCL_PA9
#define PIN_I2C0_SDA_PA8

// I2S
#define MCU_INTERFACE_I2S
#define PIN_I2S_LRCLK_PC0
#define PIN_I2S_BCLK_PC1
#define PIN_I2S_DI_PC2
#define PIN_I2S_DI_PC3
#define PIN_I2S_MCLK_PA15

// SPI 1
#define MCU_INTERFACE_SPI1
#define SPI1_CLOCK_SOURCE_HCLK
#define PIN_SPI1_SS0_PC8
#define PIN_SPI1_SCLK_PC9
#define PIN_SPI1_MISO0_PC10
#define PIN_SPI1_MOSI0_PC11

// PB15, INT1
#define MCU_INTERFACE_INT1_PB15
